name: "Prettier"

on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 6 * * *"
jobs:
  fix:
    name: Check formatting issues
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: npm ci
      - name: Check formatting issues.
        run: prettier -c .
