name: "Prettier Fixer"

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "50 20 * * *"
jobs:
  fix:
    name: Fix formatting issues
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - run: echo ".github" > ".prettierignore"

      - name: Installs dependencies
        run: npm ci
      - name: runs prettier
        run: prettier -w .

      - run: rm ".prettierignore"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prettified Code
