name: "Prettier"

on:
  push:
    branches: ["main"]
jobs:
  fix:
    name: Fix formatting issues
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --write .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prettified Code
