name: "Prettier"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "23 19 * * 3"
jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check .
  fix:
    name: Fix formatting issues
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --write .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prettified Code
