name: "Prettier"

on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 6 * * *"
jobs:
  fix:
    name: Check formatting issues
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check .
